### ISSUE TITLE
Lan host can open any vender/depositor

### ISSUE THREAD

**Issue by Acat1234** [IThundxr/CreateNumismatics#100]
### Describe the Bug

When I was hosting a lan world and someone other than me placed a vender/depositor and I tried to open it than it opens for me even though I dont own it

### Reproduction Steps

Self explanatory

### Expected Result

That I cant open it cuz I don't own it

### Operating System

Windows 11

### Mod Version

1.0.6

### Create Mod Version

0.5.1f

### Minecraft Version

1.20.1

### ModLoader and Version

Forge 47.3.5

**Comment by techno-sam** [comment]
Duplicate of #79
