### ISSUE TITLE
Unable to join single player with both numismatics and hephaestus (fabric 1.20.1 tinkers' construct port) installed

### ISSUE THREAD

**Issue by Halex000** [IThundxr/CreateNumismatics#27]
Minecraft version: 1.20.1
Fabric version: 0.15.7
Numi version: 1.0.0+fabric-mc1.20.1
Hephaestus version: 1.20.1-3.6.4.271

When having both create numismatics and hephaestus installed the player is unable to join a single player world. I have had both of these screens appear when attempting to join a single player world.
![Screenshot 2024-04-08 132443](https://github.com/Layers-of-Railways/CreateNumismatics/assets/95841600/515b094d-e6d7-4f75-911e-dd9b09958cc9)
![Screenshot 2024-04-08 142026](https://github.com/Layers-of-Railways/CreateNumismatics/assets/95841600/b9ec8913-c05b-40c6-a2c4-8f46ef11cd4c)

Mod list:
![Screenshot 2024-04-08 142349](https://github.com/Layers-of-Railways/CreateNumismatics/assets/95841600/07047165-46ef-4029-bd5c-f82cdbed50b0)

Log:
[latest.log](https://github.com/Layers-of-Railways/CreateNumismatics/files/14909747/latest.log)

**Comment by IThundxr** [comment]
This appears to be caused by hephaestus, i will talk to alpha about it

**Comment by IThundxr** [comment]
Hephaestus issue, config sync is broken.
