### ISSUE TITLE
Translatability of coin values

### ISSUE THREAD

**Issue by awrathfulvoid** [IThundxr/CreateNumismatics#31]
- Names can be properly translated, however the Value string of coins are hard coded into printing "cog/s" regardless of language, and cannot be translated. :heavy_check_mark: 
   - Assuming Spanish translation, labeling "Cog" as "Tuerca", and "Sun" as "Sol" prints correctly, but the Value string for one Sol prints "Valor: 64 cogs", when it should be "Valor: 64 Tuercas". :heavy_check_mark: 

- Summary tooltips have a lang string, but don't actually translate in-game.

- Coin value tooltips within GUI are hardcoded and cannot be translated. :heavy_check_mark:

**Comment by techno-sam** [comment]
We should maybe consider some way of allowing custom pluralization - probably just double up the translation keys, unfortunately.

For example, "Sun" would be "Zon" in Dutch, but "Zons" is not the correct plural, "Zonnen" is
