### ISSUE TITLE
Depositors will take money even if you don't have enough

### ISSUE THREAD

**Issue by TurnrDev** [IThundxr/CreateNumismatics#32]
Set a depositor for 2 money, have 1 money, use depositor - it takes your 1 coin, doesn't send any pulse but the money doesn't get deposited in the depositor, it's just... gone

**Comment by winnetrie83** [comment]
I can confirm this too.
However it does say "not enough money".
Yet if you set the required money to an amount higher, it says "not enough money" and does not consume the money. 
So far it only happens if you set the required money to 2 and having only 1 money in your inventory

**Comment by TurnrDev** [comment]
I wonder, perhaps, if it's an off by one error then?
