### ISSUE TITLE
Blocks and items missing from latest version of the mod

### ISSUE THREAD

**Issue by NeedsterW** [IThundxr/CreateNumismatics#44]
The base vendor, along with all currency below a sprocket are all missing on my end.
Taken is a screenshot of my JEI and Create: Numismatics creative tab (mod version is Forge 1.0.2 downloaded from CurseForge)

![Capture](https://github.com/Layers-of-Railways/CreateNumismatics/assets/136638877/2e3b43cb-7ea0-41fa-99da-261c3f028034)
![Capture2](https://github.com/Layers-of-Railways/CreateNumismatics/assets/136638877/fe94b309-a578-49ab-ab39-ce57256bcf10)

**Comment by IThundxr** [comment]
https://github.com/Creators-of-Create/Create/issues/6222
