### ISSUE TITLE
[Feature Request] make all coins craftable

### ISSUE THREAD

**Issue by hihroshi** [IThundxr/CreateNumismatics#45]
if coins are craftable it will make it a cool mod that i will use in future server that i will make

**Comment by hihroshi** [comment]
and make an option in config to desactivate this for pepole who dont want it craftable

**Comment by techno-sam** [comment]
Works as intended, feel free to create a datapack to add recipes. Coins are intentionally not craftable by default because each server admin will have a different way they want to run their economy.

**Comment by prog-pog** [comment]
Do the coins act like netherite? If not, a rich person could just burn all the coins without admins knowing.

Also, I am creating a data pack for this reason, its called H2GCR (Hard 2 Get Currency). you can read more about it at [here.](https://github.com/prog-pog/h2gcr)

**Comment by Szedann** [comment]
not sure why anyone would burn their coins, but just not spending them would have a similar effect

**Comment by prog-pog** [comment]
In case they are corrupt and like just stole some money off someone to get revenge.

*edit*
That would have the same effect
