### ISSUE TITLE
[Feature Request] Add 1.19.2 support

### ISSUE THREAD

**Issue by TheLPro** [IThundxr/CreateNumismatics#47]
It's the most popular version for create servers.

**Comment by SpottyTheTurtle** [comment]
Incorrect, 1.20.1 is more popular by far.

**Comment by TheLPro** [comment]
🤷‍♂️ not from what I saw. Still would be nice to have 1.19.2 support

**Comment by techno-sam** [comment]
We are not planning to provide 1.19 support. There were a number of changes in how inventories and slots worked, which will make it difficult to maintain.

**Comment by TheLPro** [comment]
bruh ok

**Comment by TheLPro** [comment]
Alright, could I fork this repo and make a 1.19.2 version?

**Comment by banna12345bob** [comment]
You could try but, like techno-sam said above, it'll be a pain.
