### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by OrixHusky** [IThundxr/CreateNumismatics#51]
Whenever I start Minecraft it crashes before getting to the main menu. Would this be due to the version of create I'm using? I have tried every version of Numismatics but none have worked.
![Screenshot 2024-04-22 015253](https://github.com/Layers-of-Railways/CreateNumismatics/assets/94772555/46727b31-5843-4f6b-9066-3462758bbb65)

https://paste.ee/p/SdB6S#

**Comment by IThundxr** [comment]
update create
