### ISSUE TITLE
[Feature Request]: Vendors allowing seleting item to do this

### ISSUE THREAD

**Issue by wolfieboy09** [IThundxr/CreateNumismatics#57]
### Describe the Suggestion

So I don't know what to name the title better, but in the "Screenshots and Videos," I have shown how a create item filter allows for you to keep the item, but in vendors, it does not do that. It would be really useful so you don't need two items to sell/buy

### Screenshots and Videos

https://github.com/Layers-of-Railways/CreateNumismatics/assets/105564186/ed207453-c5a0-4a3d-b483-6ef89b2dabbd

### Additional Context

The suggestion was also mentioned in [ They Added Money to Create? by [Shalz](https://youtu.be/yRFL0zeL5-o?si=AVO-bXYTNyVzzhEi&t=143) (mentioned there)

**Comment by banna12345bob** [comment]
I don't think that this is possible with the current UI implementation. Create filter's UI doesn't allow different stacks of items and thus couldn't be used. I may be wrong but a different implementation might have to be used.

**Comment by techno-sam** [comment]
This is planned, we just need to figure out implementation details and migration from the old system (to prevent deleting people's items)
