### ISSUE TITLE
[Feature Request] 's' on other languages

### ISSUE THREAD

**Issue by LunarFactory** [IThundxr/CreateNumismatics#59]
### Describe the Suggestion

I'm translating this mod in Korean, however in korean, there is no 's' for plural meaning. is it possible to make 's' in language key, not in code?

### Screenshots and Videos

![image](https://github.com/Layers-of-Railways/CreateNumismatics/assets/69113888/bc20d789-eddb-4599-af25-d3dad515f96e)

**Comment by Aiq0** [comment]
See #31

**Comment by nokteholda** [comment]
It also true for Indonesian as it don't uses the differentiance between singular and plural things
