### ISSUE TITLE
Unbreakable Blaze Bankers

### ISSUE THREAD

**Issue by BruhBronxy** [IThundxr/CreateNumismatics#60]
### Describe the Bug

When you shift to break a blaze banker it just replaces the block, making it unbreakable unless blown up.

### Reproduction Steps

[These can only be recreated in creative on Forge 47.2.0]

Blaze Banker
1. Place down a lit blaze burner.
2. Equip the blaze burner with a banking guide.
3. Attempting to break it when shift clicking will fail.

### Expected Result

Blaze Banker
It will be unbreakable even while shift clicking unless blown up.

### Screenshots and Videos

N/A or [Didn't Crash]

### Crash Report or Log

N/A or [Didn't Crash]

### Operating System

Windows 11

### Mod Version

1.0.4

### Create Mod Version

0.5.1f

### Minecraft Version

1.20.1

### ModLoader and Version

Forge 47.2.0

### Other Mods

N/A or [Didn't Crash]

### Additional Context

There is no conflict of mods involved in this bug

**Comment by IThundxr** [comment]
for the tab part: https://github.com/Creators-of-Create/Create/issues/6222

**Comment by BruhBronxy** [comment]
I figured out that many of the items break when on Forge 47.2.0 including the creative tab. The blaze banker issue has been solved.
