### ISSUE TITLE
Question: Can someone explain to me what the register is?

### ISSUE THREAD

**Issue by kienerxyzzy** [IThundxr/CreateNumismatics#64]
### Describe the Suggestion

For some reason, I saw textures for the register in the files, but I cannot obtain it through the creative menu or see it on the mod description. Is this a feature soon to be added?

**Comment by banna12345bob** [comment]
![image](https://github.com/Layers-of-Railways/CreateNumismatics/assets/59811283/22374c70-576c-4c7d-9adf-8e861f37f09d)
If you mean this image it is just the logo for the mod and nothing more.

**Comment by kienerxyzzy** [comment]
No, it seems to be the texture for a block.

**Comment by IThundxr** [comment]
unused at the moment
