### ISSUE TITLE
Any side of a Vendor should be able to extract/input stock

### ISSUE THREAD

**Issue by goldrat1** [IThundxr/CreateNumismatics#66]
### Describe the Suggestion

Current intended design is that the bottom side of a Vendor is used to extract stock when buying, and every other side is used to input stock when selling.

This is a problem because:
a) No other Create block works like this. Basins, Vaults, Depots, Belts, etc, all of them allow you to input and output from any side of the block. 
b) It makes it impossible to insert stock into a selling Vendor without having a funnel or chute exposed to the person buying. This means that there is no way to prevent people from stealing your stock by right-clicking whatever is inputting. Being able to insert stock from the bottom using funnels or a fanned Chute would solve this.
c) It's not mentioned in any in-game documentation
d) It changes the way the Vendor works depending if its selling or buying, which I guess would make sense if the Vendor _automatically_ took stuff from nearby inventories, but it doesn't. Funnels, chutes and belts already have a direction when you put them on a block. Why overwrite that direction arbitrarily?

In my mind there are two options to fix this:
- Let any side input or output
OR
- Let Vendors automatically take stock from Vaults/inventories underneath them.

The former makes more sense game-design wise but the latter could probably be more useful and easy to use, as setting up chutes with fans under any vendor you had could get a bit annoying. The latter would be especially useful when combining it with Item Silos from Create: Connected as they place vertically.
Personally I'd just prefer letting any side input/output but it could be a more interesting way to do it.

### Screenshots and Videos

![image](https://github.com/Layers-of-Railways/CreateNumismatics/assets/45552594/817b0769-c592-4bef-9436-e48d16afec6a)
My design for a stock input, that currently does not work :(

**Comment by Aiq0** [comment]
> Let Vendors automatically take stock from Vaults/inventories underneath them.

This would be really useful with mods like [Extended Drawers](https://modrinth.com/mod/extended-drawers)
