### ISSUE TITLE
The Sprocket complicates money conversion

### ISSUE THREAD

**Issue by marianolarre** [IThundxr/CreateNumismatics#67]
### Describe the Suggestion

**Strange value**
The sprocket fits strangely into the denominations of the coins. Bevels, Cogs, Crowns and Suns are all 8x the previous coin if you ignore the sprocket, but the sprocket takes that chain from x8-x8-x8-x8 to x8-x2-x4-x8-x8

**Repeated initials**
The names of the coins share a lot of the same initials, making it slightly inconvenient to mark prices on signs with just a letter, even if you use upper and lower case: s b S c C S. The sprocket even shares the same two initials to the spurs, so removing the sprocket would allow you to use two letters without confusion: sp, be, ~sp~, co, cr, su

**Comment by danbrown** [comment]
Well, on my server I renamed the items to Copper, Zinc, Iron, Brass, Gold and Netherite coins.
Boring? Yes, but it simplifies it enough for the common use.

**Comment by techno-sam** [comment]
We are not planning to change the denomination system. You may prefer a different system, but the way I imagined prices being communicated was something like `12C 43¤` (That is, 12 Cogs & 43 spurs).
