### ISSUE TITLE
[suggestion] Gambling

### ISSUE THREAD

**Issue by noawx** [IThundxr/CreateNumismatics#68]
### Describe the Suggestion

Where there's money, there's gambling.

Honestly I think the implementation for this could vary. It could be a redstone component that outputs a random value from 1 to 15 when given a redstone input, or even full slot machine blocks.

Basically I want some redstone/numismatic blocks to add gambling to my server.

**Comment by noawx** [comment]
The slot machine blocks would be like vendors, where they have an owner that has to fill them with payout money.

Just like vendors, they could have creative versions with unlimited payout money.

**Comment by techno-sam** [comment]
Numismatics follows Create's design philosophy of avoiding single-block solutions where possible. This can be reasonably achieved using vanilla redstone mechanics and (if you need an infinite supply) Creative Crates.

Here's a MC Wiki page describing randomizers:
https://minecraft.wiki/w/Tutorials/Randomizers

**Comment by noawx** [comment]
Ok. Thanks for the link
