### ISSUE TITLE
Confusing UI and Why it Should be Changed (Among Other Things)

### ISSUE THREAD

**Issue by ali-afk** [IThundxr/CreateNumismatics#75]
### Describe the Suggestion

The current UI is quite confusing, as it is not clear where or when you are able to place or remove items. 

Of course, this might be blamed on a player being new to the mod, but it is bad design that players are consequently expected to ask how the system works. Players should be able to easily learn it themselves in a minimal amount of time, as in some cases, this may cause players to start avoiding it entirely because they do not want to place in the effort.

<br/>
Things I'd like to see changed:

Blaze Banker:
- Bank Card Slot should at least outline WHY the card isn't fitting if not blank.

(Both) Depositors:
- Should not be limited to singular coins, but a customizable amount. (Why isn't this like the Vendor block???)
- If a coin of a higher or lower value is inputted, the resulting message should be something along the lines of ' Depositor only accepts {amount}!'
- Configuration GUI should clearly outline whether a field is the price or held stock.

Bank Terminal:
- GUI should clearly outline whether a field is the input or the output.
- GUI should be left-oriented or at least can be changed.
- Bank Card Slot should actually HOLD the card. Current system is unintuitive and causes confusion.

Cards and ID Cards:
- Tooltips should clearly state that they may only be used when bound either to a player or blaze banker.
- Tooltips should clearly state HOW they can be bound to a blaze banker.
- Tooltips should clearly state that they can be dyed.

New ID System:
- Instead of the limited inventory GUI, the trust list should use NBT to store player IDs or UUIDs onto the tile entity.
- For example, a bound ID can be placed in a slot, and then one of two buttons: 'Remove' or 'Add' can be pressed to update the list.
- Using this new system, the player should be able to input an item such as a 'Trust List' that holds many player IDs with which they can update the system.

Vendor Block:
- Coin selection should not surround the Stock Slots, keep them organsied to the left of Stock.
- Held coins should actually be labeled 'Held Coins'
- ~~(Opinion) have the capability to add dyes~~
- When in Buy mode, Stock slots should either be greyed-out or removed.
- Creative vendors should not have Stock slots.
- Block should look different if in BUY or SELL mode, and should display Sale or Buy price on the block.

Creative Tab:
- Should be populated with dyed cards.

General:
- Remove the 'Tick' button from all GUIs. Redundant because escape key.
- Use that valuable space to ADD LABELS and organise the GUI more effectively.
- If Blaze Banker can be renamed, why not everything else?
- Different GUIs are offset from the inventory GUI by varying amounts which is annoying.
-  Why does each different on-screen block renderer that appears when a GUI is opened mess with JEI differently??

Vendor Tooltip Issue (Likely due to either Create or Legendary Tooltips):

(Screenshot in the bottom)

### Screenshots and Videos

![Screenshot 2024-05-29 193656](https://github.com/Layers-of-Railways/CreateNumismatics/assets/57285258/1dda666f-f22d-4d81-8090-ccbdda95d400)

### Additional Context

**Comment by IThundxr** [comment]
tooltip issue is caused by iceberg lib

**Comment by IThundxr** [comment]
> Should not be limited to singular coins, but a customizable amount. (Why isn't this like the Vendor block???)

that's what the brass depositor is for, andesite is the sort of less advanced depositor

> Should be populated with dyed cards.

That's just bloat, we follow how create has all colors of a block show in search but not in the tab itself

> Remove the 'Tick' button from all GUIs. 

Redundant because escape key.
this is also following how create does it

**Comment by SpottyTheTurtle** [comment]
- Brass depositors already accept any arbitrary spread of coins, just like a vendor. 
- The bit about cards being immediately removed from the bank terminal slot is something we plan to change/fix. 
- Is the large arrow that many other vanilla minecraft GUIs use to designate items being moved/changed from one slot to another not a clear enough indicator? this is the first we've had report of that being the case, so I'm genuinely curious. 
- I disagree that bank/id cards should have info on how to dye them in their tooltip, as no other dyed block in all of minecraft does, plus it's one button press away with any recipe viewer mod. 
- Is there any reason why you believe the price settings should not surround the stock amount? We've yet to had any complaints about it so far, and in my personal opinion it simply looks better as-is. 
- What are you referring to by "Held coins"? 
- Also, add dyes to what? 
- I disagree with your last point about vendors, it's incredibly easy simply by hovering over one to see whether it is buying or selling and for what price. 
- The creative tab is not populated with dye cards as that increases clutter in the tab, though you can still find them just fine by searching for them. 
- Add labels to what? 
- organize what GUI? 
- Why would anything else need to be renamed? Blaze bankers are nameable so people can keep track of which account is which.

Everything else is either a good idea or something we should/are considering.

**Comment by ali-afk** [comment]
**Just note that for all the following and the original post, it is biased and opinionated.**

> Brass depositors already accept any arbitrary spread of coins, just like a vendor.

Sorry for the lack of thoroughness, I thought I had already checked.

> Is the large arrow that many other vanilla minecraft GUIs use to designate items being moved/changed from one slot to another not a clear enough indicator?

I genuinely don't know what arrow you're talking about. Possibly mods on my part disabling it?

> Is there any reason why you believe the price settings should not surround the stock amount?

The GUI seems cluttered, and overwhelmed me when I first opened it. To me, the problem is that it takes a few to process where everything goes.

> Add labels to what?

I'll answer this before the next response. To be clear, I meant adding subtle and small labels to certain parts of the GUI (of some blocks) where necessary. This is to help guide the user towards using the GUI correctly.

> What are you referring to by "Held coins"?

This is in referral to slots that hold inputted coins in blocks such as depositors and vendors, these labels should be small and merely provide indication as to where to look.

> Also, add dyes to what?

Honestly, just ignore it. I'll remove it anyways. If you are that curious, though, I mean dyeing the actual vendor blocks, which doesn't align with how Create does it as you've already stated.

> I disagree with your last point about vendors, it's incredibly easy simply by hovering over one to see whether it is buying or selling and for what price.

Perhaps it seemed harder to read because of the mods I have installed.

> organize what GUI?

As in change some GUI's to better suit the eyes, such as in the case of the vendors (in my opinion).

> Why would anything else need to be renamed? Blaze bankers are nameable so people can keep track of which account is which

My thought process is that allowing users to rename them could allow these blocks to better suit their functions (for example, vendor's), but I see where you're coming from.

Hope this answers your doubts!

**Comment by SpottyTheTurtle** [comment]
Thanks for the clarification! while I don't have anything further to add to this, here's an extremely passive aggressive screenshot of the bank terminal arrow :)
![javaw_eBMbdPt24u](https://github.com/Layers-of-Railways/CreateNumismatics/assets/69260662/b2bde616-c67b-4b86-9f59-4475bfe945b5)

**Comment by ali-afk** [comment]
> GUI should be left-oriented or at least can be changed.

*Cough Cough*

**Comment by SpottyTheTurtle** [comment]
Great idea! let's make the GUI left oriented. Bottom-left-oriented, I should say. :3
