### ISSUE TITLE
Vendor Breaking

### ISSUE THREAD

**Issue by OminousDiscovery** [IThundxr/CreateNumismatics#76]
### Describe the Suggestion

When breaking the vendor its coded to say press shift to break it. However some people (such as my self) use other buttons like control to crouch so it would be nice to change it so instead the "Hold (Player Set Crouch Keybind) to break this block.

### Screenshots and Videos

![2024-05-30_13 27 49](https://github.com/Layers-of-Railways/CreateNumismatics/assets/150559423/b4b5912a-864e-4286-b318-7ed1c12f30c7)

### Additional Context

do you like ferrets?

**Comment by IThundxr** [comment]
Implemented in https://github.com/Layers-of-Railways/CreateNumismatics/commit/ad6d6e60b68761d455ad813c668f153bab2de156

> do you like ferrets?

yes
