### ISSUE TITLE
Config to Limit Breaking Vendors to Owners 

### ISSUE THREAD

**Issue by wavian** [IThundxr/CreateNumismatics#83]
### Describe the Suggestion

Title is relatively explanatory. While vendors are a great way to trade items between players, there is always going to be that small group that would rather just steal the resources, preventing vendors from being broken by non-owners by default is likely overkill however, it would be nice to have a config option to prevent their destruction from whoever didn't place them, similar to a claim except only extending to the vendors.

**Comment by SpottyTheTurtle** [comment]
this is already how the work

**Comment by wavian** [comment]
It seems to get ignored when I tried it out by modifying the NBT of the owner or using Carpet fake players.
