### ISSUE TITLE
Virtual item in tarde item slot

### ISSUE THREAD

**Issue by HySand** [IThundxr/CreateNumismatics#84]
### Describe the Suggestion

Allow Virtual item in trade-item slot so users don't need to store at least one to buy the item. Also add JEI support so they can drag items to that slot.

### Screenshots and Videos

![image](https://github.com/Layers-of-Railways/CreateNumismatics/assets/77628540/cfad7545-6027-4f0e-94de-aee68bf1b46c)

**Comment by AngelOfCreation** [comment]
I like this idea. Good suggestion OP.
