### ISSUE TITLE
Make coins data-driven

### ISSUE THREAD

**Issue by Dweblenod** [IThundxr/CreateNumismatics#95]
### Describe the Suggestion

Instead of using a Class called CoinItem, use json files to define what items can be coins and how much they are worth. The benefit would be that the value-relationship of the current coins can be changed and it would allow currency from other mods to fit into the system.

**Comment by AngelOfCreation** [comment]
The problem I can see with this is that the ATM GUI only has slots for 6 coins, and that can't easily be changed dynamically. So if you tried to add additional items as coins it wouldn't work. It would however be simpler to let you change the values of the current coins in relation to the others.

**Comment by Dweblenod** [comment]
> The problem I can see with this is that the ATM GUI only has slots for 6 coins, and that can't easily be changed dynamically. So if you tried to add additional items as coins it wouldn't work. It would however be simpler to let you change the values of the current coins in relation to the others.

True! Although I imagine if you added arrow buttons, you could keep those 6 slots but have their representative coin shift back and forth upon pressing the arrow. New currency could be shifted into view without tampering with the basic layout of the GUI. The arrows could be invisible or grayed out if no extra currency is present

**Comment by AngelOfCreation** [comment]
> > The problem I can see with this is that the ATM GUI only has slots for 6 coins, and that can't easily be changed dynamically. So if you tried to add additional items as coins it wouldn't work. It would however be simpler to let you change the values of the current coins in relation to the others.
> 
> True! Although I imagine if you added arrow buttons, you could keep those 6 slots but have their representative coin shift back and forth upon pressing the arrow. New currency could be shifted into view without tampering with the basic layout of the GUI. The arrows could be invisible or grayed out if no extra currency is present

That's a decent option. I'd like to put forth my support for scroll functionality if this gets implemented!

**Comment by techno-sam** [comment]
This is not practical with the current UIs - Bank Terminal, Depositors, Vendors, etc. It also doesn't necessarily lend itself to clean, consistent conversions in the Bank Terminal.
