### ISSUE TITLE
Vendor wrongly displaying insufficient funds when connected to a banker account via card

### ISSUE THREAD

**Issue by ghost** [IThundxr/CreateNumismatics#98]
### Describe the Bug

A normal [non-creative] shop set to BUY items from players, and linked to a Banker account with a card that has money in it, still wrongly displays "No funds available, contact [my name]" - even tho the funds are on the account, and selling items to it DOES work.

### Reproduction Steps

1. Make a Banker account and link Card to it
2. Put funds in the account
3. Make a normal Vendor 
4. Set it to BUY an item, and put in the Card connected to the account which has money in it

### Expected Result

The shop will function and buy items, the money disappears from the linked Banker account as expected, but the Vendor block keeps displaying "No funds, contact [playername]"

### Screenshots and Videos

![image](https://github.com/user-attachments/assets/9bd133d8-b812-4f1a-8599-0e4780aea28d)
![image](https://github.com/user-attachments/assets/485f2646-2b06-4f54-93aa-5b2bdf1b6bf1)
![image](https://github.com/user-attachments/assets/0923836c-c1d4-44ff-82ee-ffc63695d274)

### Operating System

Windows 11

### Mod Version

1.0.6

### Create Mod Version

0.5.1f

### Minecraft Version

1.20.1

### ModLoader and Version

Forge 47.3.3

### Additional Context

We're running a modpack of over 280 mods. Project page for reference:
https://www.curseforge.com/minecraft/modpacks/arcanum-dei-reforged

**Comment by techno-sam** [comment]
Is `LordSavien` authorized by the blaze banker (owner or in the trust list)?

**Comment by techno-sam** [comment]
Nevermind, was able to reproduce in Dev. Will be fixed in 1.7.0
